"""Single visual token authority shared by all SIGEH executables."""

from __future__ import annotations


def visual_theme_tokens(is_dark=False):
    """Return the semantic visual contract shared by Billing and Admisión.

    The legacy names at the end of each palette deliberately remain aliases.
    Admisión V15 still consumes them while its Qt-compat widgets are migrated,
    but no surface is allowed to invent a second light/dark palette.
    """
    if is_dark:
        tokens = {
            "mode": "oscuro",
            "window_bg": "#0A1420",
            "content_bg": "#0D1927",
            "panel_bg": "#111E2E",
            "panel_elevated_bg": "#16283A",
            "input_bg": "#0F1B2A",
            "input_hover_bg": "#142437",
            "input_disabled_bg": "#182636",
            "table_bg": "#0F1B2A",
            "table_alt_bg": "#142235",
            "table_header_bg": "#1B3650",
            "popup_bg": "#16283A",
            "menu_bg": "#16283A",
            "tooltip_bg": "#21384D",
            "border": "#36516A",
            "border_strong": "#58728B",
            "border_focus": "#72C7F5",
            "text_primary": "#E5EEF8",
            "text_secondary": "#B8C6D6",
            "text_muted": "#AAB8C8",
            "text_disabled": "#8EA1B2",
            "text_on_accent": "#FFFFFF",
            "selection_bg": "#28577E",
            "selection_text": "#FFFFFF",
            "accent": "#49B8F2",
            "accent_hover": "#72C7F5",
            "success": "#228B5A",
            "warning": "#C88A2C",
            "danger": "#D25160",
            "info": "#2E9DC2",
            "success_bg": "#163A2D",
            "warning_bg": "#3A2E14",
            "danger_bg": "#3A2027",
            "info_bg": "#17354A",
            "success_text": "#C0F5D9",
            "warning_text": "#FFE3A3",
            "danger_text": "#FFB9C0",
            "info_text": "#D0ECFF",
            "button_primary_bg": "#1976B9",
            "button_primary_hover": "#258FDC",
            "button_primary_text": "#FFFFFF",
            "button_secondary_bg": "#233A50",
            "button_secondary_hover": "#2D4A64",
            "button_secondary_text": "#F2F6FA",
            "button_neutral_bg": "#283847",
            "button_neutral_hover": "#34495C",
            "button_neutral_text": "#F2F6FA",
            "button_success_bg": "#237A4A",
            "button_success_hover": "#2E915C",
            "button_success_text": "#FFFFFF",
            "button_warning_bg": "#8C5A0A",
            "button_warning_hover": "#A66E19",
            "button_warning_text": "#FFFFFF",
            "button_danger_bg": "#B83B48",
            "button_danger_hover": "#D25160",
            "button_danger_text": "#FFFFFF",
            "checkbox_indicator_bg": "#0F1B2A",
            "checkbox_indicator_border": "#6A8299",
            "checkbox_checked_bg": "#49B8F2",
            "checkbox_checkmark": "#07111F",
            "scrollbar_track": "#0D1927",
            "scrollbar_handle": "#3F5C75",
            "scrollbar_hover": "#58728B",
        }
    else:
        tokens = {
            "mode": "claro",
            "window_bg": "#EEF2F6",
            "content_bg": "#F5F8FB",
            "panel_bg": "#FFFFFF",
            "panel_elevated_bg": "#E8F0F7",
            "input_bg": "#FFFFFF",
            "input_hover_bg": "#F7FAFD",
            "input_disabled_bg": "#E5EBF1",
            "table_bg": "#FFFFFF",
            "table_alt_bg": "#F7FAFD",
            "table_header_bg": "#DCE9F5",
            "popup_bg": "#FFFFFF",
            "menu_bg": "#FFFFFF",
            "tooltip_bg": "#24364C",
            "border": "#A9BACB",
            "border_strong": "#7B91A7",
            "border_focus": "#1769AA",
            "text_primary": "#1F2A37",
            "text_secondary": "#405267",
            "text_muted": "#566678",
            "text_disabled": "#7C8B9A",
            "text_on_accent": "#FFFFFF",
            "selection_bg": "#276FB8",
            "selection_text": "#FFFFFF",
            "accent": "#1769AA",
            "accent_hover": "#0F5D9B",
            "success": "#237A4A",
            "warning": "#A16207",
            "danger": "#B42318",
            "info": "#0E7490",
            "success_bg": "#E6F5EC",
            "warning_bg": "#FFF3D6",
            "danger_bg": "#FDECEC",
            "info_bg": "#EDF4FD",
            "success_text": "#175C36",
            "warning_text": "#704600",
            "danger_text": "#8D1914",
            "info_text": "#17445A",
            "button_primary_bg": "#1769AA",
            "button_primary_hover": "#0F5D9B",
            "button_primary_text": "#FFFFFF",
            "button_secondary_bg": "#E8F0F7",
            "button_secondary_hover": "#D8E5F0",
            "button_secondary_text": "#25384C",
            "button_neutral_bg": "#E7EDF3",
            "button_neutral_hover": "#D5E0EA",
            "button_neutral_text": "#263238",
            "button_success_bg": "#237A4A",
            "button_success_hover": "#1A663C",
            "button_success_text": "#FFFFFF",
            "button_warning_bg": "#A16207",
            "button_warning_hover": "#975800",
            "button_warning_text": "#FFFFFF",
            "button_danger_bg": "#B42318",
            "button_danger_hover": "#8D1914",
            "button_danger_text": "#FFFFFF",
            "checkbox_indicator_bg": "#FFFFFF",
            "checkbox_indicator_border": "#61788E",
            "checkbox_checked_bg": "#1769AA",
            "checkbox_checkmark": "#FFFFFF",
            "scrollbar_track": "#E4EAF0",
            "scrollbar_handle": "#9CB0C2",
            "scrollbar_hover": "#718AA1",
        }

    tokens.update(
        {
            # Compatibility aliases for the existing billing/Admisión callers.
            "bg": tokens["window_bg"],
            "root": tokens["window_bg"],
            "text": tokens["text_primary"],
            "muted": tokens["text_muted"],
            "muted_text": tokens["text_muted"],
            "entry": tokens["input_bg"],
            "card": tokens["panel_bg"],
            "card2": tokens["panel_elevated_bg"],
            "surface": tokens["panel_elevated_bg"],
            "tree": tokens["table_bg"],
            "heading": tokens["table_header_bg"],
            "alt_bg": tokens["table_alt_bg"],
            "separator": tokens["border"],
            "sel_bg": tokens["selection_bg"],
            "selected_bg": tokens["selection_bg"],
            "sel_text": tokens["selection_text"],
            "selected_fg": tokens["selection_text"],
            "title_color": tokens["accent"],
            "button_fg": tokens["text_on_accent"],
            "button_text": tokens["text_on_accent"],
            "accent2": tokens["info"],
            "audit_bg": tokens["info_bg"],
            "audit_text": tokens["info_text"],
        }
    )
    return tokens
